name: Import all repos from org into monorepo

on:
  workflow_dispatch: {}   # Actions 탭에서 수동 실행 가능

jobs:
  import:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout monorepo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

      # 예시: 조직의 Leader-Car 저장소 불러오기
      - name: Import Leader-Car
        run: |
          git remote add leader https://github.com/Platooning-ANTREES-with-LIG-Nex1/Leader-Car.git
          git fetch leader
          git subtree add --prefix=src/Leader-Car leader main

      # 여기에 다른 14개 저장소도 같은 방식으로 추가
      # - name: Import AnotherRepo
      #   run: |
      #     git remote add another https://github.com/Platooning-ANTREES-with-LIG-Nex1/AnotherRepo.git
      #     git fetch another
      #     git subtree add --prefix=src/AnotherRepo another main

      - name: Push changes
        run: |
          git push origin main
